%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\isaia\OneDrive - Olin College of Engineering\Documents\QEA Final Project\outputs\distilbert-base-uncased_top6_20251217_201521\confusion_matrix.csv
%
% Auto-generated by MATLAB on 17-Dec-2025 21:21:17

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7"];
opts.SelectedVariableNames = ["Var2", "Var3", "Var4", "Var5", "Var6", "Var7"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");

% Import the data
confusion_matrix = readtable("C:\Users\isaia\OneDrive - Olin College of Engineering\Documents\QEA Final Project\outputs\distilbert-base-uncased_top6_20251217_201521\confusion_matrix.csv", opts);

%% Convert to output type
confusion_matrix = table2array(confusion_matrix);

%% Clear temporary variables
clear opts