%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\isaia\OneDrive - Olin College of Engineering\Documents\QEA Final Project\outputs\distilbert-base-uncased_top6_20251217_201521\confusion_matrix.csv
%
% Auto-generated by MATLAB on 17-Dec-2025 21:18:59

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["true_label", "Bordeaux_styleRedBlend", "CabernetSauvignon", "Chardonnay", "PinotNoir", "RedBlend", "SauvignonBlanc"];
opts.SelectedVariableNames = "true_label";
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["true_label", "Bordeaux_styleRedBlend", "CabernetSauvignon", "Chardonnay", "PinotNoir", "RedBlend", "SauvignonBlanc"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["true_label", "Bordeaux_styleRedBlend", "CabernetSauvignon", "Chardonnay", "PinotNoir", "RedBlend", "SauvignonBlanc"], "EmptyFieldRule", "auto");

% Import the data
confusion_matrix_labels = readmatrix("C:\Users\isaia\OneDrive - Olin College of Engineering\Documents\QEA Final Project\outputs\distilbert-base-uncased_top6_20251217_201521\confusion_matrix.csv", opts);


%% Clear temporary variables
clear opts