%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\isaia\OneDrive - Olin College of Engineering\Documents\QEA Final Project\winemag-data_first150k.csv
%
% Auto-generated by MATLAB on 05-Dec-2025 15:06:42

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "country", "description", "designation", "points", "price", "province", "region_1", "region_2", "variety", "winery"];
opts.VariableTypes = ["double", "categorical", "string", "string", "double", "double", "categorical", "categorical", "categorical", "categorical", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["description", "designation", "winery"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["country", "description", "designation", "province", "region_1", "region_2", "variety", "winery"], "EmptyFieldRule", "auto");

% Import the data
winemag_data_first150k = readtable("C:\Users\isaia\OneDrive - Olin College of Engineering\Documents\QEA Final Project\winemag-data_first150k.csv", opts);


%% Clear temporary variables
clear opts